server:
  port: 8001
spring:
  application:
    name: consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
    fetch-registry: true
    register-with-eureka: true