server:
  port: 7000
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
    fetch-registry: false
    register-with-eureka: false